### ISSUE TITLE
Feature Request - каждый тип тех сервиса на отдельной странице 

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-example#35]
Сейчас, 13 типов объектов на одной странице и нельзя дать прямую ссылку на конкретный реестр. 
Я слабо себе представляю возможность работы над стольким количеством одновременно. 

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/d59c360c-d9e0-4ea5-9001-342dfdf47b6c)

**Comment by SychevIgor** [comment]
копия запроса https://github.com/SEAFTeam/seaf-core/issues/25

**Comment by SychevIgor** [comment]
@kmyachin fyi

**Comment by talifan** [comment]
Вообще не понимаю о чём речь.

**Comment by SychevIgor** [comment]
пример open source- лучших практик... пол года не обращали внимания. затем написали что не поняли, и сразу зыкрыли. 

попробую обьяснить 
![image](https://github.com/user-attachments/assets/c3e8261a-7116-40a8-a20f-71c98ac4489f)

сейчас, есть штук 13 разных обьектов ТА архитектуры типа userdevice, dc,az и т.п. они сейчас все на одной странице выводятся и нет отдельных страниц под типы та сервисов. сводный отчет - замечательно, но бесполезно. условный датацентр хочется искать на странице, где есть ровна одна таблица с датацентрами, а не в сводном отчете.

**Comment by talifan** [comment]
![image](https://github.com/user-attachments/assets/43518592-06aa-4c53-be7e-9784ea3e00e8)
Вот же отдельная страница с DC и всем остальным. В меню выбрать DC и нажать. Будет отдельная страница.

**Comment by SychevIgor** [comment]
![image](https://github.com/user-attachments/assets/e84ab602-911f-4984-a0ff-65dba8559bf7)

**Comment by SychevIgor** [comment]
когда я запрос делал - не было в левой панеле списка вот такого. наши товарищи из других отделов- не хотят навигацию изучать, хотят в поиске искать. а, чтобы в поиске найти - надо, чтобы страница была в левом меню
