### ISSUE TITLE
Bug Report - не добавлять 2 раза interface/root.yaml

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-example#43]
2 раза не надо добавлять interface/root.yaml -одного должно хватить

https://github.com/SEAFTeam/seaf-dzo-example/blob/aa5d7db8d9483a8a2bbdb5a9413ab8ba922acdd1/dochub.yaml#L32
https://github.com/SEAFTeam/seaf-dzo-example/blob/aa5d7db8d9483a8a2bbdb5a9413ab8ba922acdd1/architecture/root.yaml#L7

**Comment by talifan** [comment]
Исправлено https://github.com/SEAFTeam/seaf-dzo-example/pull/84

**Comment by SychevIgor** [comment]
полгода спустя... хорошо, что таки забрали
